version: "2"

services:
  webserver:
    volumes:
      - ".:/var/www/"
    environment:
      VIRTUAL_HOST: "www.${PROJECT_NAME}-${PROJECT_SUFFIX}.docker"
      VIRTUAL_PORT: 80

  elasticsearch:
    environment:
      VIRTUAL_HOST: "elasticsearch.${PROJECT_NAME}-${PROJECT_SUFFIX}.docker"
      VIRTUAL_PORT: 9200

  php:
    volumes:
      - "../Environment/Docker/php/ssmtp.conf:/etc/ssmtp/ssmtp.conf"
      - "../Environment/Docker/php/mailcatcher.ini:/etc/php/7.0/cli/conf.d/mailcatcher.ini"
      - ".:/var/www/html/"
    links:
      - "mailcatcher"

  mailcatcher:
    image: "schickling/mailcatcher"
    environment:
      VIRTUAL_HOST: "mailcatcher.${PROJECT_NAME}-${PROJECT_SUFFIX}.docker"
      VIRTUAL_PORT: 1080
