version: "2"

services:
  webserver:
    volumes:
      - "./../app/:/var/www/"
    environment:
      VIRTUAL_HOST: "www.${PROJECT_NAME}"
      VIRTUAL_PORT: 80

  elasticsearch:
    environment:
      VIRTUAL_HOST: "elasticsearch.${PROJECT_NAME}"
      VIRTUAL_PORT: 9200

  php:
    volumes:
      - "./Docker/php/ssmtp.conf:/etc/ssmtp/ssmtp.conf"
      - "./Docker/php/mailcatcher.ini:/etc/php/7.0/cli/conf.d/mailcatcher.ini"
      - "./../app/:/var/www/html/"
    links:
      - "mailcatcher"

  mailcatcher:
    image: "schickling/mailcatcher"
    environment:
      VIRTUAL_HOST: "mailcatcher.${PROJECT_NAME}"
      VIRTUAL_PORT: 1080
