version: "2"

volumes:
  mysqlData:
    driver: local
  elasticsearchData:
    driver: local

services:
  webserver:
    image: "nginx:1.11"
    links:
      - "php"
    volumes:
      - "../Environment/Files/nginx.conf:/etc/nginx/nginx.conf"
      - ".:/var/www/"
      - "../Volumes/${PROJECT_NAME}/logs/webserver/:/var/log/nginx/"
    env_file:
      - "./Build/Environment/.env"

  php:
    build: "../Environment/Docker/php"
    expose:
      - "9000"
    volumes:
      - "../Environment/Files/php-fpm-pool.conf:/etc/php/7.0/fpm/pool.d/www.conf"
      - ".:/var/www/"
    working_dir: "/var/www/"
    env_file:
      - "./Build/Environment/.env"
    links:
      - "db"
      - "elasticsearch"
      - "redis"

  db:
    image: "mariadb:10.0"
    env_file:
      - "./Build/Environment/.env"
    volumes:
      - "mysqlData:/var/lib/mysql"
      - "../Volumes/${PROJECT_NAME}/logs/db/:/var/log/mysql/"
      - "../Environment/Files/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf"

  elasticsearch:
    image: "elasticsearch:2.3"
    env_file:
      - "./Build/Environment/.env"
    volumes:
      - "elasticsearchData:/usr/share/elasticsearch/data"
      - "../Environment/Files/elasticsearch/java.policy:/home/elasticsearch/.java.policy"
      - "../Environment/Files/elasticsearch/elasticsearch-2.3.yml:/usr/share/elasticsearch/config/elasticsearch.yml"

  redis:
    image: "redis:3.0"
